"""Documentation generated from the configuration, so it cannot drift from what the code does.

    docs/data_dictionary.md   every feed: steward, supplier, delivery, layouts, columns and their
                              classification (direct identifier, quasi-identifier, clinical, ...)
    docs/rules.md             the rule registry: every rule, its dimension, action and retry policy
    docs/lineage.md           supplier file -> raw -> staging -> clean -> published -> dbt -> documents

`pophealth docs` rewrites them; `pophealth docs --check` (and a test) fails if they are stale.
"""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path

import yaml

from .feeds import feed_spec
from .settings import REPO, Settings

GENERATED = "<!-- Generated by `pophealth docs` from config/ and dbt/; do not edit by hand. -->"


def _table(headers: list[str], rows: list[list]) -> list[str]:
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    for r in rows:
        out.append("| " + " | ".join(str(v).replace("|", "/") for v in r) + " |")
    return out


def data_dictionary(settings: Settings) -> str:
    lines = [
        GENERATED,
        "",
        "# Data dictionary",
        "",
        "Every column the pipeline accepts, where it comes from, and how it is classified. The classification "
        "drives de-identification: every document path built from a `direct_identifier` column must be "
        "transformed by the demo policy, and a test enforces it.",
        "",
    ]
    counts = Counter((c["classification"]) for contract in settings.contracts.values() for c in contract.columns)
    lines += _table(
        ["classification", "columns", "meaning"],
        [
            [
                "direct_identifier",
                counts["direct_identifier"],
                "identifies a person on its own (name, record number, full dates, contact details)",
            ],
            [
                "quasi_identifier",
                counts["quasi_identifier"],
                "identifies in combination (sex, race and ethnicity, language, ZIP3, year of birth)",
            ],
            ["clinical", counts["clinical"], "health information"],
            ["operational", counts["operational"], "identifiers of records and places, statuses"],
            ["reference", counts["reference"], "codes from public code systems"],
        ],
    ) + [""]
    for feed in settings.feeds_order:
        c = settings.contracts[feed]
        lines += [
            f"## {feed} - {c.title}",
            "",
            c.description,
            "",
            f"- **Steward:** {c.steward}",
            f"- **Supplier:** {c.supplier}",
            f"- **Delivery:** every {c.cadence_days} days, grace {c.grace_days} day(s); "
            + ("full snapshot, history kept (type 2)" if c.snapshot else "incremental, merged by natural key"),
            f"- **Natural key:** {', '.join(c.natural_key)}",
            f"- **Accepted date formats:** {', '.join(f'`{f}`' for f in c.date_formats)} (detected per file)",
            f"- **Publishes:** {', '.join(f'published.{t}' for t in c.published)}",
            "",
        ]
        rows = []
        for source in c.sources.values():
            for layout in source.layouts:
                rows.append(
                    [
                        source.name,
                        f"`{source.pattern.pattern}`",
                        f"v{layout.version}",
                        layout.change_record or "",
                        ", ".join(f"{k} -> {v}" for k, v in layout.columns.items()),
                    ]
                )
        lines += (
            ["### Supplier layouts", ""]
            + _table(["source", "file name", "layout", "change record", "source column -> canonical"], rows)
            + [""]
        )
        lines += (
            ["### Columns", ""]
            + _table(
                ["column", "type", "classification", "description"],
                [[f"`{col['name']}`", col["type"], col["classification"], col["description"]] for col in c.columns],
            )
            + [""]
        )
    return "\n".join(lines).rstrip() + "\n"


def _rule_notes(rule) -> str:
    p = rule.params
    notes = []
    if rule.type == "volume":
        notes.append(
            f"stop below {p.get('min_ratio')}x the usual delivery"
            + (
                f" (usual = median of recent loads; checked once it is at least {p['min_baseline_rows']} rows)"
                if p.get("min_baseline_rows")
                else ""
            )
        )
    if rule.type == "completeness":
        notes.append(f"at least {float(p['min_share']):.0%} recorded")
    if "block_if_rate_over" in p:
        notes.append(f"stops the file if more than {float(p['block_if_rate_over']):.0%} of rows fail")
    if rule.type in ("parse", "mapped", "in_reference", "on_roster", "not_future", "closed_period"):
        notes.append(f"column `{p['column']}`")
    if rule.type == "required":
        notes.append("columns " + ", ".join(f"`{c}`" for c in p["columns"]))
    if rule.message:
        notes.append(rule.message)
    return "; ".join(notes)


def rule_catalogue(settings: Settings) -> str:
    rules = [(f, r) for f in settings.feeds_order for r in settings.contracts[f].rules]
    actions = Counter(r.action for _, r in rules)
    dims = Counter(r.dimension for _, r in rules)
    lines = [
        GENERATED,
        "",
        "# Data-quality rules",
        "",
        f"{len(rules)} rules across {len(settings.feeds_order)} feeds, declared in `config/contracts/`. "
        "Actions: "
        + ", ".join(f"{k} {v}" for k, v in sorted(actions.items()))
        + ". Dimensions: "
        + ", ".join(f"{k} {v}" for k, v in sorted(dims.items()))
        + ".",
        "",
        "- **block** - the whole file is stopped; the feed does not publish past it until it is re-delivered, "
        "or a steward accepts it (it loads) or waives it (the feed publishes without it).",
        "- **quarantine** - the row is held with the rule's id. If every rule it failed is *retryable*, it is "
        "re-checked on later runs and released when it passes (a patient registered late, a code mapping "
        "added); otherwise it waits for a steward.",
        "- **repair** - fixed because the fix is provable (leading zeros, letter case), and recorded.",
        "- **warn** - recorded and reported; the row goes through.",
        "",
        "Every firing is a row in `audit.row_findings` (run, file, row, rule, detail), summarised per run in "
        "`dq_scorecard.csv`.",
        "",
    ]
    for feed in settings.feeds_order:
        c = settings.contracts[feed]
        lines += [f"## {feed}", ""]
        lines += _table(
            ["id", "rule", "type", "dimension", "action", "retry", "notes"],
            [
                [r.id, r.title, r.type, r.dimension, r.action, "yes" if r.retryable else "", _rule_notes(r)]
                for r in c.rules
            ],
        ) + [""]
    return "\n".join(lines).rstrip() + "\n"


def _dbt_edges() -> tuple[list[tuple[str, str]], list[str]]:
    edges, models = [], []
    for path in sorted((REPO / "dbt" / "models").rglob("*.sql")):
        name = path.stem
        models.append(name)
        text = path.read_text(encoding="utf-8")
        for src in re.findall(r"source\('published',\s*'([a-z_]+)'\)", text):
            edges.append((f"published.{src}", name))
        for ref in re.findall(r"ref\('([a-z_]+)'\)", text):
            edges.append((ref, name))
    return edges, models


def lineage(settings: Settings) -> str:
    def node(name: str) -> str:
        return re.sub(r"[^A-Za-z0-9_]", "_", name)

    lines = [
        GENERATED,
        "",
        "# Lineage",
        "",
        "From supplier file to the de-identified copy. Generated from the contracts, the dbt models' "
        "`ref()`/`source()` calls, and `config/collections.yaml`.",
        "",
        "```mermaid",
        "flowchart LR",
    ]
    edges: list[tuple[str, str]] = []
    labels: dict[str, str] = {}
    groups: dict[str, list[str]] = {
        "Supplier files": [],
        "raw (text, per layout)": [],
        "staging -> clean": [],
        "published": [],
        "dbt": [],
        "documents": [],
        "de-identified": [],
    }
    for feed in settings.feeds_order:
        c = settings.contracts[feed]
        spec = feed_spec(settings, feed)
        clean = f"clean.{spec.clean_table}"
        for source in c.sources.values():
            f_node = f"file_{source.name}"
            labels[f_node] = f"{source.name} files"
            groups["Supplier files"].append(f_node)
            for layout in source.layouts:
                raw = f"raw.{feed}__{source.name}__v{layout.version}"
                labels[raw] = raw
                groups["raw (text, per layout)"].append(raw)
                edges.append((f_node, raw))
                edges.append((raw, f"staging.{feed}"))
        labels[f"staging.{feed}"] = f"staging.{feed}"
        labels[clean] = clean
        groups["staging -> clean"] += [f"staging.{feed}", clean]
        edges.append((f"staging.{feed}", clean))
        edges.append((f"staging.{feed}", f"quarantine.{feed}"))
        labels[f"quarantine.{feed}"] = f"quarantine.{feed}"
        groups["staging -> clean"].append(f"quarantine.{feed}")
        for table in c.published:
            labels[f"published.{table}"] = f"published.{table}"
            groups["published"].append(f"published.{table}")
            edges.append((clean, f"published.{table}"))
    dbt_edges, models = _dbt_edges()
    for m in models:
        labels[m] = m
        groups["dbt"].append(m)
    labels["measure_definitions"] = "measure_definitions (seed)"
    groups["dbt"].append("measure_definitions")
    edges += dbt_edges
    collections = yaml.safe_load((settings.config_dir / "collections.yaml").read_text(encoding="utf-8"))["collections"]
    for name, spec in collections.items():
        doc = f"documents.{name}"
        labels[doc] = f"{name} documents"
        groups["documents"].append(doc)
        for read in spec.get("reads", []):
            edges.append((read.split(".", 1)[1] if not read.startswith("published.") else read, doc))
        edges.append((doc, "demo_copy"))
    labels["demo_copy"] = "demo-site copy (demo_site policy)"
    labels["safe_harbor"] = "Safe Harbor extract"
    groups["de-identified"] += ["demo_copy", "safe_harbor"]
    for src in ("published.patients", "int_patient_facts", "measure_patient_results"):
        edges.append((src, "safe_harbor"))
    for group, members in groups.items():
        lines.append(f'    subgraph {node(group)}["{group}"]')
        for m in dict.fromkeys(members):
            lines.append(f'        {node(m)}["{labels.get(m, m)}"]')
        lines.append("    end")
    for a, b in dict.fromkeys(edges):
        lines.append(f"    {node(a)} --> {node(b)}")
    lines += ["```", ""]
    return "\n".join(lines).rstrip() + "\n"


def generate_docs(settings: Settings, check: bool = False) -> list[str]:
    outputs = {
        REPO / "docs" / "data_dictionary.md": data_dictionary(settings),
        REPO / "docs" / "rules.md": rule_catalogue(settings),
        REPO / "docs" / "lineage.md": lineage(settings),
    }
    stale = []
    for path, text in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current != text:
            stale.append(str(path.relative_to(REPO)).replace("\\", "/"))
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
    return stale


def generated_paths() -> list[Path]:
    return [REPO / "docs" / n for n in ("data_dictionary.md", "rules.md", "lineage.md")]
